spring.application.name=productService
#spring.mongodb.uri=mongodb://admin:admin123@localhost:27017/productdb?authSource=admin
#server.port=8084

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#eureka.instance.prefer-ip-address=true
spring.config.import=optional:configserver:http://localhost:8092